INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Kraven the Hunter", 5.4, 48000, 127, "Action.K");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Twisters", 6.5, 162000, 122, "Action.K");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Gladiator II", 6.5, 220000, 148, "Action.K");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Sonic the Hedgehog 3", 6.9, 54000, 110, "Action.K");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Pushpa: The Rule - Part 2", 6.1, 55000, 201, "Action.K");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Venom: The Last Dance", 6.0, 110000, 110, "Action.K");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Dune: Part Two", 8.5, 616000, 166, "Action.K");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Ministry of Ungentlemanly Warfare", 6.8, 132000, 122, "Action.K");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Deadpool & Wolverine", 7.6, 483000, 128, "Action.K");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Furiosa: A Mad Max Saga", 7.5, 281000, 148, "Action.K");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Lord of the Rings: The War of the Rohirrim", 6.3, 29000, 134, "Action.K");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Borderlands", 4.7, 46000, 101, "Action.K");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Civil War", 7.0, 233000, 109, "Action.K");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Elevation", 5.6, 20000, 91, "Action.K");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Beekeeper", 6.3, 153000, 105, "Action.K");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Solo Leveling: ReAwakening", 8.8, 91000, 121, "Action.K");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Carry-On", 6.5, 161000, 119, "Action.K");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Count of Monte-Cristo", 7.6, 33000, 178, "Action.K");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Fall Guy", 6.8, 217000, 126, "Action.K");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("William Tell", 5.8, 19000, 133, "Action.K");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Hellboy: The Crooked Man", 4.5, 13000, 99, "Action.K");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Rebel Ridge", 6.8, 86000, 131, "Action.K");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Damsel", 6.1, 108000, 110, "Action.K");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Marco", 6.9, 20000, 145, "Action.K");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Homestead", 5.4, 34000, 112, "Action.K");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Crow", 4.7, 33000, 111, "Action.K");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Road House", 6.2, 166000, 121, "Action.K");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Transformers One", 7.6, 48000, 104, "Action.K");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Red One", 6.3, 138000, 123, "Action.K");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Argylle", 5.6, 92000, 139, "Action.K");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Kingdom of the Planet of the Apes", 6.9, 150000, 145, "Action.K");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Killer's Game", 5.8, 16000, 104, "Action.K");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Freaky Tales", 6.5, 382, 106, "Action.K");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Madame Web", 4.0, 100000, 116, "Action.K");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Bad Boys: Ride or Die", 6.5, 98000, 115, "Action.K");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Old Guy", 5.2, 19000, 94, "Action.K");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Godzilla x Kong: The New Empire", 6.1, 120000, 115, "Action.K");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Love Lies Bleeding", 6.6, 56000, 104, "Action.K");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Thelma", 7.0, 22000, 98, "Action.K");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Land of Bad", 6.6, 50000, 113, "Action.K");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Dirty Angels", 4.3, 32000, 104, "Action.K");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Aftermath", 5.1, 36000, 97, "Action.K");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Monkey Man", 6.8, 90000, 121, "Action.K");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Blitz", 6.2, 16000, 120, "Action.K");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Union", 5.4, 52000, 107, "Action.K");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Uglies", 4.7, 32000, 100, "Action.K");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Cash Out", 4.8, 29000, 92, "Action.K");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Survive", 4.6, 22000, 90, "Action.K");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Azrael", 5.4, 10000, 86, "Action.K");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Drive-Away Dolls", 5.4, 23000, 84, "Action.K");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Moana 2", 6.7, 91000, 100, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Flow", 7.9, 62000, 85, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Twisters", 6.5, 161000, 122, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Gladiator II", 6.5, 219000, 148, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Day the Earth Blew Up: A Looney Tunes Movie", 7.0, 27000, 91, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Sonic the Hedgehog 3", 6.9, 53000, 110, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Mufasa: The Lion King", 6.6, 48000, 118, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Venom: The Last Dance", 6.0, 109000, 110, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Dune: Part Two", 8.5, 615000, 166, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Deadpool & Wolverine", 7.6, 482000, 128, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Paddington in Peru", 6.7, 18000, 106, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Furiosa: A Mad Max Saga", 7.5, 281000, 148, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Lord of the Rings: The War of the Rohirrim", 6.3, 28000, 134, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Borderlands", 4.7, 46000, 101, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Civil War", 7.0, 233000, 109, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Despicable Me 4", 6.2, 63000, 94, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Solo Leveling: ReAwakening", 8.8, 86000, 121, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Count of Monte-Cristo", 7.6, 33000, 178, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Inside Out 2", 7.5, 212000, 96, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Damsel", 6.1, 108000, 110, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Transformers One", 7.6, 48000, 104, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Red One", 6.3, 138000, 123, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Kingdom of the Planet of the Apes", 6.9, 150000, 145, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Return", 6.2, 76000, 116, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Freaky Tales", 6.5, 377, 106, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Madame Web", 4.0, 99000, 116, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Bad Boys: Ride or Die", 6.5, 98000, 115, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Godzilla x Kong: The New Empire", 6.1, 120000, 115, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Love Lies Bleeding", 6.6, 56000, 104, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Ghostbusters: Frozen Empire", 6.1, 92000, 115, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Night of the Zoopocalypse", 6.3, 354, 91, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Wallace & Gromit: Vengeance Most Fowl", 7.5, 33000, 82, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Uglies", 4.7, 32000, 100, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Spaceman", 5.7, 42000, 107, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Survive", 4.6, 21000, 90, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Harold and the Purple Crayon", 5.7, 8000, 90, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Kung Fu Panda 4", 6.3, 67000, 94, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Attack on Titan the Movie: The Last Attack", 9.2, 14000, 145, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Garfield Movie", 5.7, 24000, 101, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Kalki 2898 AD", 7.0, 66000, 180, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Descendants: The Rise of Red", 4.7, 69000, 91, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Atlas", 5.6, 55000, 118, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Arthur the King", 7.0, 34000, 107, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Spellbound", 5.6, 65000, 109, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Rebel Moon - Part Two: The Scargiver", 5.3, 59000, 122, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("My Penguin Friend", 6.7, 48000, 97, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Hitpig", 5.1, 853, 86, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Winner", 6.5, 23000, 103, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Monster Summer", 5.7, 35000, 97, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("No Way Up", 4.6, 10000, 90, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Orion and the Dark", 6.3, 17000, 93, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Unholy Trinity", 7.9, 49, 93, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("A Sloth Story", 5.6, 188, 90, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Family Pack", 5.5, 87000, 94, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Megamind vs. The Doom Syndicate", 2.5, 55000, 83, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Best Christmas Pageant Ever", 6.8, 6000, 99, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Lost on a Mountain in Maine", 6.1, 11000, 98, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Justice League: Crisis on Infinite Earths - Part One", 6.2, 83000, 93, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Justice League: Crisis on Infinite Earths - Part Three", 6.1, 44000, 94, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Saving Bikini Bottom: The Sandy Cheeks Movie", 3.7, 38000, 82, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("River of Blood", 5.4, 16000, 86, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Now or Never!", 2.1, 17000, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Empire", 5.2, 12000, 110, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Bookworm", 6.0, 18000, 103, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Sasquatch Sunset", 5.4, 53000, 88, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Thelma the Unicorn", 5.7, 29000, 93, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Hanu Man", 7.7, 29000, 158, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Buffalo Kids", 6.6, 646, 93, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Something in the Water", 4.1, 45000, 86, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("I, the Executioner", 6.3, 16000, 118, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Raqa", 5.9, 119, 107, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Price of Money: A Largo Winch Adventure", 5.0, 11000, 100, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("That Christmas", 6.8, 17000, 91, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Badland Hunters", 5.9, 12000, 107, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("My Hero Academia: You're Next", 7.0, 19000, 110, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Noah's Ark", 4.3, 626, 96, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Courier", 6.0, 43000, 101, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Guest from the Future", 6.0, 12000, 141, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Goat Life", 7.1, 47000, 173, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Manjummel Boys", 8.2, 27000, 135, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Tiger's Apprentice", 5.7, 21000, 84, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Wages of Fear", 4.6, 41000, 104, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Twisters", 2.5, 315, 86, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Ultraman: Rising", 6.9, 62000, 117, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Justice League: Crisis on Infinite Earths - Part Two", 5.5, 52000, 94, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Doraemon the Movie: Nobita's Earth Symphony", 6.6, 14000, 115, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Cult Killer", 4.8, 27000, 105, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Angels Fallen: Warriors of Peace", 4.9, 58000, 103, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Lost Tiger", 7.9, 40, 90, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Autumn and the Black Jaguar", 5.6, 973, 100, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Operation Blood Hunt", 3.4, 462, 93, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Woody Woodpecker Goes to Camp", 4.5, 25000, 100, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Storm Crashers", 6.3, 551, 88, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("My Freaky Family", 6.4, 390, 86, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Anaconda", 4.9, 603, 84, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Golden Kamuy", 6.3, 25000, 127, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Dragonkeeper", 5.7, 16000, 98, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Firing Squad", 5.4, 5000, 93, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Magician's Raincoat", 5.7, 90, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Dalia y el Libro Rojo", 6.5, 60, 107, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("No Chains No Masters", 6.4, 486, 98, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Unspeakable: Beyond the Wall of Sleep", 5.9, 39, 90, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Sixty Minutes", 5.7, 51000, 88, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Last Redemption", 6.7, 34000, 122, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("WWII: Operation Phoenix", 6.6, 63, 106, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Demon Slayer: Kimetsu No Yaiba - To the Hashira Training", 7.1, 83000, 104, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Crayon Shin-chan: Ora's Dinosaur Diary", 6.5, 317, 106, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("200% Wolf", 6.0, 13000, 98, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Rebellious", 6.0, 166, 94, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Saint-Exupéry", 5.5, 240, 98, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Bambi: A Tale of Life in the Woods", 5.6, 152, 85, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Escape", 6.4, 19000, 94, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Man and Witch: The Dance of a Thousand Steps", 5.5, 327, 94, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Devil's Knight", 5.4, 781, 90, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Thangalaan", 6.6, 65000, 156, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("A.R.M", 7.1, 85000, 150, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Panda Bear in Africa", 5.5, 310, 84, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("A Legend", 4.7, 863, 129, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Overlord: The Sacred Kingdom", 7.0, 704, 135, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Kanguva", 4.5, 14000, 152, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Niko: Beyond the Northern Lights", 6.2, 308, 86, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Cells at Work!", 6.8, 172, 109, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Robin and the Hoods", 4.4, 504, 100, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Never Look Away", 7.2, 250, 85, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Eat the Night", 6.2, 422, 106, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Spiders on a Plane", 5.6, 362, 78, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Escape from the 21st Century", 6.6, 825, 98, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Planetquake", 3.0, 283, 85, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("War of the Worlds: Extinction", 3.0, 181, 84, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Barroz: Guardian of Treasures", 3.6, 958, 155, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Roadkill", 3.6, 673, 90, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Bade Miyan Chote Miyan", 3.8, 39000, 163, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Forest", 6.5, 20, 77, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Meanwhile on Earth", 6.0, 878, 89, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Ayalaan", 6.0, 4000, 155, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("All for One", 1.2, 610, 97, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Last Ronin", 4.9, 232, 121, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Pimpinero: Blood and Oil", 5.6, 541, 121, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Rally Caps", 5.5, 136, 100, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Bionic", 4.3, 17000, 110, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Keepers of the 5 Kingdoms", 4.1, 217, 109, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("School of Magical Animals 3", 5.9, 298, 105, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Memes & Nightmares", 5.7, 78, 81, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Last of Us: Immunity", 6.3, 13, 64, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Mountain", 6.6, 152, 89, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Shrek 5: The Contract - A Fan Made Film", 7.0, 18, 84, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("My Fathers' Daughter", 6.6, 71, 78, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("No Time to Spy: A Loud House Movie", 6.4, 437, 81, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Kingdom", 7.9, 85, 133, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Bureau 749", 4.1, 503, 123, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("A Trip Elsewhere", 5.5, 97, 93, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Slave and the Sorcerer", 6.7, 38, 86, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Tanning Zone", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Treasure Trackers", 5.8, 158, 92, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Going Viral", 6.8, 50, 90, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Dongeng Sang Kancil", 8.3, 80, 99, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Gladiators", 6.4, 37, 95, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Return to Wickensburg", 4.8, 23, 88, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Chico Bento e a Goiabeira Maraviosa", 7.6, 659, 90, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("This Too Shall Pass", 0.0, 0, 105, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Phantom Warrior", 2.4, 553, 119, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Casagrandes Movie", 5.6, 657, 89, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Satu - Year of the Rabbit", 9.3, 48, 93, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Z-Mom", 4.7, 43, 90, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Maya, donne-moi un titre", 6.4, 48, 61, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Big City Greens the Movie: Spacecation", 6.2, 536, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("One Million Babes BC", 3.3, 35, 75, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Fox & Hare Save the Forest", 5.9, 193, 71, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Its Name Was Mormo", 3.6, 113, 93, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Witch Hunter", 5.2, 23, 80, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Ivan Tsarevich i Seryy Volk 6", 5.6, 78, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Mobile Suit Gundam SEED Freedom", 6.6, 929, 124, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Ghost Island", 7.1, 43, 95, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Odio el verano", 5.1, 554, 103, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("My Oni Girl", 6.0, 17000, 112, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Trifole", 7.5, 44, 100, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Big Trip 3: Race Around the World", 5.7, 51, 85, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Elli and the Ghostly Ghost Train", 5.0, 89, 86, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Gracie and Pedro: Pets to the Rescue", 5.1, 260, 87, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Fuuto PI: Portrait of Kamen Rider Skull", 7.6, 31, 82, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Kodaikanal", 9.2, 67, 173, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Letuchiy korabl", 3.8, 291, 100, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Five Friends", 6.7, 857, 112, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Adventures of Jurassic Pet: Return to the Wild", 5.5, 53, 90, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Bremenskie muzykanty", 4.6, 662, 115, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Rocky Road to Berlin", 7.2, 13000, 104, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Captain Miller", 6.5, 86000, 157, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Empire Queen: The Golden Age of Magic", 3.2, 204, 148, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Earthquake Underground", 3.3, 191, 83, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Little Emma", 5.7, 103, 106, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Hain", 2.9, 45, 95, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Major Grom: The Game", 6.1, 18000, 168, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Zak & Wowo: The Legend of Lendarys", 5.7, 86, 85, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Kalvan", 5.6, 984, 142, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Buddy", 3.8, 340, 137, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Game On", 2.6, 347, 85, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Legend Hunters", 5.3, 19, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Gaami", 6.4, 2000, 147, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Epidemic", 5.8, 69, 95, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Diving Into the Darkness", 9.1, 82, 96, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Kvitebjørn", 5.9, 53, 85, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Abudeka Is Back", 5.3, 31, 120, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Amazon Bullseye", 5.3, 185, 113, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Vertical", 5.2, 118, 111, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Teenz", 4.4, 861, 122, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Jathara", 6.4, 1000, 129, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Formed Police Unit", 4.6, 473, 120, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Powder Pup", 6.2, 73, 89, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("I Heart Robots", 4.6, 23000, 76, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("At Her Feet", 7.5, 40, 100, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Oculus", 6.0, 15, 113, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Tay 2: Ebabil Takimi", 5.5, 36, 78, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("I Left My Heart in Colombia", 9.1, 415, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Seven Seas Seven Hills", 8.7, 86, 90, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Historia de pastores", 5.6, 28, 80, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Stinky Summer", 5.9, 45, 90, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Goldbeak", 4.9, 127, 94, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Dead Dead Demon's Dededede Destruction", 7.0, 139, 120, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Tri kota. Zimnie kanikuly", 6.1, 27, 65, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("My Redneck Neighbor: Chapter 2 - Let the Games Begin", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Un lío de millones", 6.0, 50, 91, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Marianengraben", 7.6, 69, 87, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Yaren Leylek", 5.9, 26, 95, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Bull Shark 3", 3.6, 72, 76, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Jurassic Triangle", 2.5, 277, 84, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Death Game", 6.3, 24, 88, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Epic of Gilgamesh", 0.0, 0, 79, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Sentinelese", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Tracing the Divide", 8.7, 162, 84, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Captain Avispa", 5.8, 172, 96, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Worlds Divide", 8.0, 36, 120, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Road Wars: Max Fury", 2.0, 349, 83, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Baba Yaga spasaet Novyy god", 4.4, 113, 99, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Sunlight", 7.9, 17, 96, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Cazatesoros", 6.6, 24, 106, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Naa Saami Ranga", 4.5, 12000, 150, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Finding Christmas", 7.5, 10, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Yolki 11", 4.6, 165, 92, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Gepack", 6.6, 360, 97, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Daye: Seret ahl el Daye", 7.8, 15, 104, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Nintama Rantaro Dokutake Ninja-tai Saikyou no Gunshi", 6.8, 14, 90, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Dünya Varmis", 7.4, 49, 100, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Get Close 2", 5.7, 45, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("My Redneck Neighbor: Chapter 1 - The Rednecks Are Coming", 5.0, 7, 74, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Waves of Madness", 5.9, 17, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Jake Danger and the Sword of the Explorer", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Wonderful Precure! The Movie! Doki Doki Game no Sekai de Daiboken", 6.8, 28, 71, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Killer Witches from Outer Space", 7.1, 77, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Dragon Ball Z Kai", 8.4, 66, 82, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Mong Vuot", 5.3, 116, 96, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Arctic Hollow", 2.3, 179, 70, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Next to Us", 4.9, 220, 125, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Traveller", 5.2, 202, 134, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Star City Murders", 4.1, 141, 79, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Luigi's Mansion", 6.0, 17, 60, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Spirit Riser", 6.7, 33, 98, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Son of the Wolf", 0.0, 0, 82, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Taklee Genesis x Worlds Collide", 5.5, 387, 146, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Birds Flying East", 5.8, 559, 100, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Si Juki the Movie: Harta Pulau Monyet", 6.0, 115, 107, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Sam and Colby: The Legends of the Paranormal", 4.8, 303, 98, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("STEVE (A Minecraft Movie)", 0.0, 0, 61, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Tulang Belulang Tulang", 7.0, 39, 95, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Turma da Mônica Jovem: Reflexos do Medo", 2.8, 255, 88, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Appu", 8.6, 181, 92, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Friendly Fire", 6.6, 30, 105, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("LasseMajas detektivbyrå - Maskoten som försvann", 6.0, 54, 90, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Emma", 0.0, 0, 90, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Ahl Al Kahf", 5.2, 238, 120, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Six Nine Five (695)", 7.0, 705, 137, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Masha i Medved v kino: Park chudes", 7.0, 16, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Askepote", 3.5, 80, 72, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Ognivo", 5.4, 214, 105, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Rocky and Bullwinkle", 9.7, 11, 100, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Troy the Bharat Putra", 5.5, 31, 134, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Oscar Wilde About America", 0.0, 0, 98, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Permafrost", 5.7, 112, 80, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Analogistan", 0.0, 0, 85, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Uttarakaanda", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Tipppsy", 8.1, 32, 115, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Håkan Bråkan 2", 5.4, 129, 92, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Bernadotte, Louise & Napoleon", 0.0, 0, 74, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Dünya Mali: Eksi Bir", 7.2, 16, 133, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Mr. Blue Shirt: The Inspiration", 4.9, 10, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("This Land of Mine", 8.0, 5, 90, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Kaizen", 7.3, 638, 160, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Artifact", 0.0, 0, 108, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Apples Gang: The Movie by Wright", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Secret of Pin-Up Island", 7.4, 92, 107, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Game of Death - The six Doors to Hell", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Space Ranger", 3.4, 78, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("A Christmas Carol", 9.8, 11, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Vikaasaparva", 8.7, 540, 134, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Stranded Pearl", 6.0, 27, 90, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Very Last Christmas", 8.5, 11, 75, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Puffins & the Magic Portal", 7.6, 30, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Joachim and the Apocalypse", 7.2, 12, 90, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Trail", 7.2, 19, 80, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Güzel Bir Rüya", 4.9, 41, 79, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Advent", 7.5, 6, 119, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Knight", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Surge of Power: Where There's Smoke", 6.5, 13, 68, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Transformers Prime: Galavatron's Revenge", 0.0, 0, 104, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Mountain Boy", 8.2, 17, 93, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Steal the Naughty List", 6.6, 114, 90, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Xibalba Monster", 6.0, 20, 76, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Kade", 6.5, 15, 92, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Die Chaosschwestern und Pinguin Paul", 5.7, 66, 100, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Tokusou Sentai Dekaranger 20th: Fireball Booster", 7.1, 29, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Elephant Steps", 6.8, 39, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Spider-Man: Blue", 5.9, 11, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Samaya bolshaya luna", 2.4, 128, 105, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Two Breaths", 8.1, 21, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Triple 7: They Said It Couldn't Be Done", 8.5, 13, 97, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Nanoshark", 5.4, 18, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Zoloto Umalty", 5.0, 103, 109, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Fights Break Sphere 3", 4.7, 8, 81, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Duffle Bag Boy", 6.9, 56, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Dikkie Dik 2: Een Nieuwe Vriend voor Dikkie Dik", 7.4, 71, 70, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Eye of the Salamander", 7.9, 20, 81, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Yasmeen's Element", 7.6, 20, 76, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Umbrella Fairy", 5.5, 48, 95, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Kral Sakir: Devler Uyandi", 5.4, 64, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Silex and the City, le film", 4.9, 47, 77, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Chernyy zamok", 7.8, 17, 115, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Dead Dead Demon's Dededede Destruction Zenpen", 7.0, 136, 120, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Igrisca ne damo!", 6.9, 26, 79, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Chhota Bheem and the Curse of Damyaan", 4.8, 23000, 145, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Benjamin Bat", 8.1, 28, 75, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Cândido", 6.3, 58, 99, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Iron Dusk", 5.2, 15, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Backrooms", 6.2, 7, 63, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Heavens: The Boy and His Robot", 6.3, 21, 98, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Shanghai Story", 8.1, 55, 71, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Bratya", 2.8, 111, 103, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Tapori Nayak", 8.6, 19, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Piraty galaktiki Barrakuda", 4.4, 79, 92, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Jaunt", 8.4, 7, 78, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Mama", 8.5, 7, 100, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Dikkie Dik en de Verdwenen Knuffel", 7.2, 127, 62, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Nature Cat's Nature Movie Special Extraordinaire", 7.2, 17, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Cold Father", 7.0, 17, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("One Day the Movie", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Vasilisa i khraniteli vremeni", 3.1, 66, 98, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Seeking the King", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Mr Zoo Keeper", 8.1, 15, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Yoshi Movie", 7.7, 12, 105, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Oyunda Kal: Eglence Arenasi", 2.7, 35, 92, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Nothing Unusual", 9.7, 12, 92, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Manyunya. Priklyucheniya v derevne", 5.9, 115, 84, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Moy dikiy drug", 6.7, 52, 100, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Mai Martaba", 4.8, 9, 86, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Quantum Supremacy", 0.0, 0, 70, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Road to Dreamland", 0.0, 0, 90, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Anytime", 8.9, 20, 62, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Tri bogatyrya. Ni dnya bez podviga", 5.7, 62, 61, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("No More Trouble - Cosa rimane di una tempesta", 8.4, 17, 97, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Hope & Glory", 6.6, 142, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Family Vacation", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Tur s Ivanushkami", 5.3, 157, 111, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Dans l'ombre de Marlow", 0.0, 0, 80, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Mobile Suit Gundam: Silver Phantom", 6.1, 13, 90, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Dakar Chronicles", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("23 Horas", 7.2, 18, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("BAM!", 7.2, 27, 80, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Bar MoskvaChiki", 5.2, 100, 91, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Sasqualogist", 0.0, 0, 89, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("De Legende van Familie Vos", 5.7, 58, 81, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Longe da Estrada", 6.0, 9, 68, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Dreams", 0.0, 0, 106, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Wilhelm Gustloff", 8.7, 8, 110, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Pui Pui Molcar the Movie: Molmax", 7.0, 7, 69, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Hyacinthe", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Kiyma: Orman Kanunlari", 4.3, 34, 81, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Life with Quincy 3", 0.0, 0, 73, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Manyunya. Priklyucheniya v Moskve", 5.6, 109, 87, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Poklad", 4.6, 34, 100, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Moy lyubimyy chempion", 2.3, 419, 95, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Ballad of Straw Hat Sam", 9.2, 10, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Space in Between", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Adam i Eva", 5.1, 92, 95, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Untitled Crunchyroll/Sony", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Il ricercatore", 5.8, 7, 71, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Shadows of Betrayal: Chronicles of Ian Blair", 7.3, 12, 65, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Operation Wakaliga: Fate and Blood", 6.7, 11, 66, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Penelope & Everly's Holiday Adventure", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Minecraft But I Survive Again in Parkour Civilization", 9.3, 22, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Fallen Leaves, Broken Lighters", 7.7, 7, 96, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Return", 0.0, 0, 90, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Oro Negro", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Petualangan Anak Penangkap Hantu", 6.0, 24, 99, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Dragon Gate Inn", 0.0, 0, 90, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Goodbye Hamdi", 6.2, 8, 85, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Lo carga el diablo", 7.6, 22, 104, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Dream 1", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Dogman Territory: Werewolves in the Land Between the Lakes", 5.4, 31, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("La Familia del Barrio: La Película", 4.0, 6, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Pirates & Slaves", 5.8, 6, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Fatal Expedition", 3.9, 24, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Suchana", 9.0, 527, 90, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Last Five Days: The Freak Building", 3.8, 58, 61, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("I racconti del mare", 0.0, 0, 89, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Toy Kids: The Movie", 0.0, 0, 65, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Mesken (Messuage)", 7.5, 36, 102, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Wonderland", 6.8, 12, 120, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Bigfoot Prophecy", 4.8, 23, 117, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("My Only Relative.", 0.0, 0, 105, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Novyy god v Beryozovke", 7.1, 97, 94, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Boom!", 8.3, 10, 90, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Tayna Chyornoy Ruki", 5.7, 22, 84, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("YA - medved", 4.9, 61, 97, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Art Work", 0.0, 0, 91, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("V potoke trekh stikhiy", 5.3, 40, 85, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Gladiator II: The Art and Making of the Ridley Scott Film", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Spooky Society", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Farm", 0.0, 0, 104, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Molar", 0.0, 0, 135, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Lost Coast", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Frankenstein Theater: The Magic Sword", 4.4, 22, 82, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Poymay sobaku, esli smozhesh", 3.5, 36, 96, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Road Long", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Fat Chance! the Movie", 7.6, 6, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Applepictures the Poseidon Legacy", 6.4, 19, 84, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Wheelies Inc", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Antarctic Voyage", 6.8, 6, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Montserrat, Integral 107", 0.0, 0, 85, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Dandelion", 8.9, 9, 95, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Warrior Awang and Master Tok Gajah", 4.6, 472, 118, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Gumshoe Jon and the Mystery of the Saucer Men - The Even Better Version", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("La bruja del bosque oscuro", 0.0, 0, 92, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Dushu", 0.0, 0, 96, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Piri Reis: The Incredible Chart", 6.8, 21, 138, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Whites Only: Ade's Extremist Adventure", 7.0, 27, 65, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Jackpot", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Luccas e Gi em: Dinossauros", 3.5, 27, 91, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Let's Go! Anpanman: Baikinman and Lulun", 6.5, 7, 64, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Kage & Celeste", 0.0, 0, 69, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Final Kick", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Turbozavry. God drakona", 9.2, 42, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Ngesot", 4.8, 18, 87, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Colour Palette", 9.0, 23, 87, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Nijari", 0.0, 0, 106, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Dracu Ra", 5.5, 34, 106, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Le mystère de Waza", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Militant Monster 2024", 8.8, 28, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Cursed Waters: Creature of Lake Okanagan", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Pra Sempre", 0.0, 0, 75, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Chyortov kamen", 6.4, 9, 105, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Target Jeremy", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Abar Arownne Din Ratri", 7.8, 7, 111, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Xiang Xi Gui Shi", 0.0, 0, 72, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Road to Paradise", 0.0, 0, 76, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Alex and Mia's Awesome Movie!!", 0.0, 0, 75, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Ba Jie", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Mukhadrakon", 5.3, 16, 109, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Tales from the Table", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("DCLXVI", 0.0, 0, 200, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Kyle and the Last Emerald 2", 8.4, 7, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Era Oculta", 0.0, 0, 80, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Suvorovets 1944", 5.6, 8, 90, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Purgatorio", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Dragon's Tomb", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Banana Boat", 5.7, 19, 78, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The 9th Raider", 0.0, 0, 105, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Gen Ben Ting bu xia lai", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Puffins: Arctic Games", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Selebryata", 3.6, 20, 93, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Príncipe Lu e a Lenda do Dragão", 4.2, 27, 90, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Wild Boys", 0.0, 0, 119, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Cacophony the Animated Movie", 0.0, 0, 81, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Lost and Found", 0.0, 0, 60, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("A Babá - Operação Game Over", 4.8, 10, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("L'Elisir di Leonardo da Vinci e la Banda del Buffardello", 0.0, 0, 90, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Qianhe xiansheng", 0.0, 0, 82, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("LUDA", 7.2, 6, 86, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("EP Break the Multiverse", 0.0, 0, 76, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Mortadella", 0.0, 0, 90, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Old Wild Mob", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Lion Dog", 0.0, 0, 122, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Huaquero Tierra Maldita", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Florp's Solar Vacation", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Novogodniy ekspress", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Eroi in crestere: Aventura celor 7 ani de acasa", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Ghost of Annie Lee", 0.0, 0, 103, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Moving Targets", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Bigfoot prophecy 2", 0.0, 0, 118, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Harmonie", 0.0, 0, 74, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Domain 1 - Antarctica", 0.0, 0, 74, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Skazochnyy patrul. Shou prodolzhayetsya", 7.2, 11, 65, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Changle Zhen Gui Shi", 0.0, 0, 88, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Sathur: Part1", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Across America", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Altered", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Koopas", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Non succederà più", 0.0, 0, 90, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Long Quiet", 0.0, 0, 94, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Línguas de Fogo", 0.0, 0, 69, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Maverick from the Edge", 0.0, 0, 107, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Lost & Found", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Yan Hu Ji Hua", 0.0, 0, 90, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Same Picture Group Holiday Special", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Tobia e i colori del mondo", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Superman: Jubilation", 0.0, 0, 176, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Marraia", 0.0, 0, 77, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("PW V: Tears of the Fallen", 8.2, 11, 60, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Stand at Alder Creek", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Seed", 0.0, 0, 100, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Beyond existence", 5.8, 10, 95, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Sehnsucht nach Firdaws", 8.5, 6, 103, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("I crossed America with $0.01", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("StarGazer: The Need of the Many", 5.0, 9, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("I'm Professional", 3.7, 8, 95, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Les Nouveaux Candides", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Lost Colony", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("New Day", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Salem, SOS-ed!", 0.0, 0, 91, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Bragow", 0.0, 0, 120, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Embers of Domsheria", 0.0, 0, 95, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Filmmaker", 0.0, 0, 97, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Deux hommes un destin", 0.0, 0, 94, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Aruanda - Sentido da Vida", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Pray", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Okhota na russkogo geniya", 2.6, 7, 71, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Carjorski Clan: Tale of the Fallen Knight", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Pizza Guys", 0.0, 0, 89, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Bear Kid: Super Hero", 0.0, 0, 80, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Boyz", 0.0, 0, 132, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("TAÏ: 33 jours dans la dernière forêt d'Afrique de l'Ouest", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Madeline & Silverfrost", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Adrian", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Robo Puffin", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Isle: Alpha One", 8.4, 7, 97, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Unhappy 25 Years Little Brat", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Kingfish 2", 7.9, 10, 72, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Katzie in Marokko", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Upanga Kingdom", 0.0, 0, 115, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("I am the girl 3 me and my girlfriend", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("ABC Life: The Movie", 0.0, 0, 60, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Tripping", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("NJPW SMP: The Movie", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Once upon a bridge in Vietnam", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Oda: Vlucht door de Eeuwen", 6.4, 7, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Psycho Rhythm", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Veyshal Movie", 0.0, 0, 120, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Melissa's Birthday", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("7 Day Fast", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Tinpot & Yello", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Isola degli sguardi", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("One in a million chance", 0.0, 0, 70, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Emu War: A Subtle Examination of the Sheer Caucasity of Colonialism", 0.0, 0, 0, "Adventure");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Moana 2", 6.7, 93000, 100, "Animation");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Flow", 7.9, 64000, 85, "Animation");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Day the Earth Blew Up: A Looney Tunes Movie", 7.0, 29000, 91, "Animation");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Mufasa: The Lion King", 6.6, 50000, 118, "Animation");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Wild Robot", 8.2, 154000, 102, "Animation");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Lord of the Rings: The War of the Rohirrim", 6.3, 29000, 134, "Animation");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Despicable Me 4", 6.2, 63000, 94, "Animation");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Solo Leveling: ReAwakening", 8.8, 91000, 121, "Animation");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Inside Out 2", 7.5, 213000, 96, "Animation");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("IF", 6.4, 57000, 104, "Animation");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Memoir of a Snail", 7.8, 16000, 95, "Animation");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Transformers One", 7.6, 48000, 104, "Animation");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Night of the Zoopocalypse", 6.3, 363, 91, "Animation");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Wallace & Gromit: Vengeance Most Fowl", 7.5, 33000, 82, "Animation");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Spermageddon", 5.9, 657, 80, "Animation");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Harold and the Purple Crayon", 5.7, 8000, 90, "Animation");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Kung Fu Panda 4", 6.3, 67000, 94, "Animation");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Attack on Titan the Movie: The Last Attack", 9.2, 14000, 145, "Animation");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Garfield Movie", 5.7, 24000, 101, "Animation");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Spellbound", 5.6, 67000, 109, "Animation");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Watchmen: Chapter I", 7.0, 63000, 83, "Animation");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Look Back", 7.8, 14000, 0, "Animation");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Hitpig", 5.1, 863, 86, "Animation");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Piece by Piece", 6.9, 52000, 93, "Animation");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Most Precious of Cargoes", 7.1, 779, 81, "Animation");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Orion and the Dark", 6.3, 17000, 93, "Animation");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Grand Theft Hamlet", 6.9, 17000, 89, "Animation");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("A Sloth Story", 5.6, 189, 90, "Animation");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Megamind vs. The Doom Syndicate", 2.5, 55000, 83, "Animation");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Watchmen: Chapter II", 7.0, 28000, 90, "Animation");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Justice League: Crisis on Infinite Earths - Part One", 6.2, 84000, 93, "Animation");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Justice League: Crisis on Infinite Earths - Part Three", 6.1, 44000, 94, "Animation");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Saving Bikini Bottom: The Sandy Cheeks Movie", 3.7, 38000, 82, "Animation");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Remarkable Life of Ibelin", 8.2, 12000, 103, "Animation");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Thelma the Unicorn", 5.7, 29000, 93, "Animation");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Buffalo Kids", 6.6, 647, 93, "Animation");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("That Christmas", 6.8, 17000, 91, "Animation");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("My Hero Academia: You're Next", 7.0, 19000, 110, "Animation");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Noah's Ark", 4.3, 630, 96, "Animation");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Tiger's Apprentice", 5.7, 21000, 84, "Animation");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Ultraman: Rising", 6.9, 63000, 117, "Animation");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Colors Within", 7.1, 852, 101, "Animation");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Glassworker", 7.4, 16000, 98, "Animation");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Justice League: Crisis on Infinite Earths - Part Two", 5.5, 52000, 94, "Animation");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Doraemon the Movie: Nobita's Earth Symphony", 6.6, 14000, 115, "Animation");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Lost Tiger", 7.8, 41, 90, "Animation");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("10 Lives", 5.9, 19000, 88, "Animation");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Woody Woodpecker Goes to Camp", 4.5, 25000, 100, "Animation");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Dan Da Dan: First Encounter", 8.2, 26000, 83, "Animation");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Storm Crashers", 6.3, 552, 88, "Animation");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Anora", 7.6, 163000, 139, "ComedyK");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Moana 2", 6.7, 93000, 100, "ComedyK");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Day the Earth Blew Up: A Looney Tunes Movie", 7.0, 29000, 91, "ComedyK");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("A Real Pain", 7.1, 79000, 90, "ComedyK");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Sonic the Hedgehog 3", 6.9, 54000, 110, "ComedyK");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Emilia Pérez", 5.4, 85000, 132, "ComedyK");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Ministry of Ungentlemanly Warfare", 6.8, 132000, 122, "ComedyK");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Deadpool & Wolverine", 7.6, 483000, 128, "ComedyK");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("My Dead Friend Zoe", 6.7, 18000, 103, "ComedyK");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Paddington in Peru", 6.7, 18000, 106, "ComedyK");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Riff Raff", 5.8, 18000, 103, "ComedyK");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Borderlands", 4.7, 46000, 101, "ComedyK");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Despicable Me 4", 6.2, 63000, 94, "ComedyK");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Saturday Night", 6.9, 29000, 109, "ComedyK");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Challengers", 7.0, 152000, 131, "ComedyK");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("F*** Marry Kill", 5.3, 2000, 97, "ComedyK");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Fall Guy", 6.8, 217000, 126, "ComedyK");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Kinds of Kindness", 6.5, 58000, 164, "ComedyK");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Beetlejuice Beetlejuice", 6.7, 144000, 105, "ComedyK");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Inside Out 2", 7.5, 213000, 96, "ComedyK");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("A Different Man", 6.9, 28000, 112, "ComedyK");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Idea of You", 6.3, 72000, 115, "ComedyK");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("IF", 6.4, 57000, 104, "ComedyK");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Nightbitch", 5.6, 19000, 99, "ComedyK");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Fly Me to the Moon", 6.6, 49000, 132, "ComedyK");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Red One", 6.3, 138000, 123, "ComedyK");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Argylle", 5.6, 92000, 139, "ComedyK");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Y2K", 4.8, 10000, 91, "ComedyK");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("My Old Ass", 6.9, 38000, 89, "ComedyK");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Killer's Game", 5.8, 16000, 104, "ComedyK");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Freaky Tales", 6.5, 382, 106, "ComedyK");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Kneecap", 7.6, 17000, 105, "ComedyK");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Bad Boys: Ride or Die", 6.5, 98000, 115, "ComedyK");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("It's What's Inside", 6.6, 41000, 103, "ComedyK");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Old Guy", 5.2, 19000, 94, "ComedyK");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Eephus", 7.1, 388, 99, "ComedyK");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Thelma", 7.0, 22000, 98, "ComedyK");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Ghostbusters: Frozen Empire", 6.1, 92000, 115, "ComedyK");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Friendship", 7.4, 233, 100, "ComedyK");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Superboys of Malegaon", 8.0, 12000, 127, "ComedyK");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Mean Girls", 5.5, 37000, 112, "ComedyK");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Misericordia", 6.9, 17000, 104, "ComedyK");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Union", 5.4, 52000, 107, "ComedyK");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Night of the Zoopocalypse", 6.3, 363, 91, "ComedyK");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Wallace & Gromit: Vengeance Most Fowl", 7.5, 33000, 82, "ComedyK");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Bob Trevino Likes It", 8.1, 401, 102, "ComedyK");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Hard Truths", 7.3, 47000, 97, "ComedyK");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Miller's Girl", 5.2, 23000, 93, "ComedyK");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Snack Shack", 7.0, 12000, 112, "ComedyK");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Spermageddon", 5.9, 657, 80, "ComedyK");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Trap", 5.8, 133000, 105, "Crime");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Longlegs", 6.6, 181000, 101, "Crime");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Pushpa: The Rule - Part 2", 6.1, 55000, 201, "Crime");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Emilia Pérez", 5.4, 85000, 132, "Crime");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Order", 6.8, 39000, 116, "Crime");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Juror #2", 7.0, 93000, 114, "Crime");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Riff Raff", 5.8, 18000, 103, "Crime");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Despicable Me 4", 6.2, 63000, 94, "Crime");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Beekeeper", 6.3, 153000, 105, "Crime");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Carry-On", 6.5, 161000, 119, "Crime");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("MaXXXine", 6.3, 68000, 103, "Crime");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Wolfs", 6.5, 80000, 108, "Crime");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Rebel Ridge", 6.8, 86000, 131, "Crime");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Marco", 6.9, 20000, 145, "Crime");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Lucky Baskhar", 8.0, 30000, 148, "Crime");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Crow", 4.7, 33000, 111, "Crime");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Force of Nature: The Dry 2", 5.8, 68000, 120, "Crime");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Freaky Tales", 6.5, 382, 106, "Crime");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Seed of the Sacred Fig", 7.6, 13000, 167, "Crime");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Bad Boys: Ride or Die", 6.5, 98000, 115, "Crime");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Love Lies Bleeding", 6.6, 56000, 104, "Crime");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Misericordia", 6.9, 17000, 104, "Crime");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Monkey Man", 6.8, 90000, 121, "Crime");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Sleeping Dogs", 6.2, 21000, 110, "Crime");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Instigators", 6.2, 37000, 101, "Crime");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Beverly Hills Cop: Axel F", 6.4, 81000, 118, "Crime");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Lift", 5.5, 49000, 107, "Crime");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Maharaja", 8.4, 66000, 141, "Crime");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Killer Heat", 5.6, 13000, 95, "Crime");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Greedy People", 6.2, 11000, 112, "Crime");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Absolution", 5.2, 75000, 112, "Crime");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Long Gone Heroes", 5.2, 1000, 101, "Crime");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("In Youth We Trust", 6.8, 268, 132, "Crime");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Brothers", 5.4, 13000, 89, "Crime");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Beating Hearts", 7.0, 42000, 166, "Crime");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Armor", 3.5, 37000, 89, "Crime");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Silent Hour", 6.1, 71000, 99, "Crime");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Santosh", 7.0, 16000, 128, "Crime");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Jönssonligan kommer tillbaka", 6.0, 12000, 104, "Crime");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Twilight of the Warriors: Walled In", 7.0, 9000, 126, "Crime");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Hitpig", 5.1, 863, 86, "Crime");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Baby John", 5.4, 17000, 159, "Crime");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Blackwater Lane", 4.6, 18000, 108, "Crime");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Shadow Strays", 6.5, 9000, 144, "Crime");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Inside", 7.0, 220, 104, "Crime");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Trigger Warning", 4.6, 19000, 106, "Crime");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Boneyard", 4.1, 49000, 96, "Crime");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("The Calendar Killer", 5.4, 4000, 97, "Crime");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Dead Sea", 5.3, 53000, 88, "Crime");
INSERT INTO Imdbmovies (Title, Rating, Views, Duration, Genre) VALUES ("Mea Culpa", 4.2, 7000, 120, "Crime");
